services:
  app: 
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.14-noble
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: