version: "3.8"

services:
  app: 
    build: .
    expose:
      - "5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.14-noble
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  nginx:
    image: nginx:latest
    containter_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

volumes:
  mongo-data: