services:
  app:
    image: app:latest
    build:
      context: .
      #dockerfile: Dockerfile
    working_dir: /var/app
    environment:
      - FLASK_APP=app.py
    container_name: app
    volumes:
      - ./app.py:/var/app/app.py
    command: ["flask", "run", "--host=0.0.0.0"]
    expose:
      - "5000"
    depends_on:
      - mongo

  
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"   # optional: expose DB to host
    volumes:
      - mongo_data:/data/db   # persist data
  
  nginx:
    image: nginx:latest
    containter_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always
  
  volumes:
    mongo_data:

  # app2:
  #   image: app:latest
  #   build:
  #     context: .
  #     #dockerfile: Dockerfile
  #   working_dir: /var/app
  #   environment:
  #     - FLASK_APP=app.py
  #   container_name: app2
  #   volumes:
  #     - ./app.py:/var/app/app.py
  #   command: ["flask", "run", "--host=0.0.0.0"]
  #   ports:
  #     - "8080:5000"